package com.my.web.person;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-02T09:51:06.972+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.my.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayLove", targetNamespace = "http://service.my.com/", className = "com.my.web.person.SayLove")
    @WebMethod
    @ResponseWrapper(localName = "sayLoveResponse", targetNamespace = "http://service.my.com/", className = "com.my.web.person.SayLoveResponse")
    public java.lang.String sayLove(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
