
package com.my.user.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceIMpl", targetNamespace = "http://service.my.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceIMpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayLove", targetNamespace = "http://service.my.com/", className = "com.my.user.stub.SayLove")
    @ResponseWrapper(localName = "sayLoveResponse", targetNamespace = "http://service.my.com/", className = "com.my.user.stub.SayLoveResponse")
    public String sayLove(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
