package com.my.spring.person;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-09-02T23:31:58.437+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.ws.my.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listPerson", targetNamespace = "http://service.ws.my.com/", className = "com.my.spring.person.ListPerson")
    @WebMethod
    @ResponseWrapper(localName = "listPersonResponse", targetNamespace = "http://service.ws.my.com/", className = "com.my.spring.person.ListPersonResponse")
    public java.util.List<com.my.spring.person.Person> listPerson();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://service.ws.my.com/", className = "com.my.spring.person.AddPerson")
    @WebMethod
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://service.ws.my.com/", className = "com.my.spring.person.AddPersonResponse")
    public java.lang.String addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.my.spring.person.Person arg1
    );
}
