
package com.my.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonService1Service", targetNamespace = "http://service.my.com/", wsdlLocation = "http://192.168.1.100:9999/hello?wsdl")
public class PersonService1Service
    extends Service
{

    private final static URL PERSONSERVICE1SERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONSERVICE1SERVICE_EXCEPTION;
    private final static QName PERSONSERVICE1SERVICE_QNAME = new QName("http://service.my.com/", "PersonService1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.100:9999/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSERVICE1SERVICE_WSDL_LOCATION = url;
        PERSONSERVICE1SERVICE_EXCEPTION = e;
    }

    public PersonService1Service() {
        super(__getWsdlLocation(), PERSONSERVICE1SERVICE_QNAME);
    }

    public PersonService1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSERVICE1SERVICE_QNAME, features);
    }

    public PersonService1Service(URL wsdlLocation) {
        super(wsdlLocation, PERSONSERVICE1SERVICE_QNAME);
    }

    public PersonService1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSERVICE1SERVICE_QNAME, features);
    }

    public PersonService1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonService1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonService1
     */
    @WebEndpoint(name = "PersonService1Port")
    public PersonService1 getPersonService1Port() {
        return super.getPort(new QName("http://service.my.com/", "PersonService1Port"), PersonService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService1
     */
    @WebEndpoint(name = "PersonService1Port")
    public PersonService1 getPersonService1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.my.com/", "PersonService1Port"), PersonService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSERVICE1SERVICE_EXCEPTION!= null) {
            throw PERSONSERVICE1SERVICE_EXCEPTION;
        }
        return PERSONSERVICE1SERVICE_WSDL_LOCATION;
    }

}
